import '@styles/globals.css';

import { NextAuthProvider } from './components/Provider'
import Navbar from './components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <div className='main'>
              <div className='gradient' />
          </div>

          <main className="app">
            <Navbar />
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  )
}

